[package]
name = "cptio"
version = "1.4.1dev"

[package.build]
backend = {name = "pixi-build-python", version = "0.1.*"}
channels = [
  "https://prefix.dev/pixi-build-backends",
]

[package.host-dependencies]
setuptools = "78.1.*"

[package.run-dependencies]
xarray = "*"
