[package]
name = "cptio"
version = "1.4.1dev"

[package.build.backend]
name = "pixi-build-python"
version = "0.4.*"
channels = [
  "https://prefix.dev/pixi-build-backends",
  "conda-forge",
]

[package.host-dependencies]
setuptools = "78.1.*"

[package.run-dependencies]
xarray = "*"
