[package]
name = "cptbin"
version = "18.7.2dev0"

[package.build.backend]
name = "pixi-build-rattler-build"
version = "0.3.*"
channels = [
  "https://prefix.dev/pixi-build-backends",
  "conda-forge",
]
